version: '3'

services:
  web:
    image: gpw-web
    container_name: gpw-web
    ports:
      - 9000:80
      - 9002:9002 # vite
      - 35729:35729 # livereload
    depends_on:
      - memcached
      - mysql
    volumes:
      - .:/var/www:delegated
      - node-modules:/var/www/node_modules
      - .docker/web/nginx.conf:/etc/nginx/sites-enabled/gazelle.conf
      - .docker/web/www.conf:/etc/php/7.3/fpm/pool.d/www.conf
    environment:
      # These should match what you set for your mysql container below
      - MYSQL_USER=gazelle
      - MYSQL_PASSWORD=password

  memcached:
    image: memcached:1.5-alpine
    container_name: gpw-memcached
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: gpw-phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=gazelle
      - PMA_PASSWORD=password
    depends_on:
      - mysql
    ports:
      - 9001:80
  mysql:
    image: mariadb:10.3
    container_name: gpw-mysql
    ports:
      - 36000:3306
    volumes:
      - ./.docker/mysql/mysqld_sql_mode.cnf:/etc/mysql/conf.d/mysqld_sql_mode.cnf:delegated
      - mysql-data:/var/lib/mysql
      - ./gazelle.sql:/docker-entrypoint-initdb.d/gazelle.sql:ro
    environment:
      - MYSQL_DATABASE=gazelle
      - MYSQL_USER=gazelle
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=em%G9Lrey4^N

  sphinxsearch:
    build: ./.docker/sphinxsearch
    container_name: gpw-sphinxsearch
    depends_on:
      - mysql
      - web
    volumes:
      - sphinx-data:/var/lib/sphinxsearch/data/
      - ./.docker/sphinxsearch/sphinx.conf:/var/lib/sphinxsearch/conf/sphinx.conf
    environment:
      # These should match what you set for your mysql container above
      - MYSQL_USER=gazelle
      - MYSQL_PASSWORD=password

volumes:
  node-modules:
  mysql-data:
  sphinx-data:
